### ISSUE TITLE
create the destination service instance with plan lite and the xsuaa service Status is Inprogress 

### ISSUE THREAD

**Issue by cjpark-sapcsa** [SAP-samples/btp-hyperscaler-extension#11]
HI Team, 

i am in the step of  Step 5.4  create the destination service instance with plan lite and the xsuaa service instance with plan application by running the below command.  

\btp-hyperscaler-extension\k8s>kubectl get serviceinstances -n sapfiori
NAME                         OFFERING      PLAN          STATUS       READY   AGE
destination-instance-fiori   destination   lite          InProgress   False   24h
xsuaa-instance-fiori         xsuaa         application   InProgress   False   24h

any idea how to fix this error ? 

Best REgards

Chan JIn 

================================================================
    "status": {
                "conditions": [
                    {
                        "lastTransitionTime": "2022-08-03T03:30:30Z",
                        "message": "Error sending request GET /v1/service_instances?attach_last_operations=true\u0026fieldQuery=name+eq+%27xsuaa-instance-fiori%27+and+context%2Fclusterid+eq+%2732847e6c-2a7e-443e-b7aa-f7d6ff7ea2a5%27+and+context%2Fnamespace+eq+%27sapfiori%27\u0026labelQuery=_k8sname+eq+%27xsuaa-instance-fiori%27: Get /v1/service_instances?attach_last_operations=true\u0026fieldQuery=name+eq+%27xsuaa-instance-fiori%27+and+context%2Fclusterid+eq+%2732847e6c-2a7e-443e-b7aa-f7d6ff7ea2a5%27+and+context%2Fnamespace+eq+%27sapfiori%27\u0026labelQuery=_k8sname+eq+%27xsuaa-instance-fiori%27: unsupported protocol scheme \"\"",
                        "observedGeneration": 1,
                        "reason": "InProgress",
                        "status": "False",
                        "type": "Succeeded"
                    },
                    {
                        "lastTransitionTime": "2022-08-03T03:30:30Z",
                        "message": "",
                        "reason": "NotProvisioned",
                        "status": "False",
                        "type": "Ready"
                    }
                ],
                "observedGeneration": 1,
                "ready": "False"
            }

**Comment by cjpark-sapcsa** [comment]
\btp-hyperscaler-extension\k8s>kubectl get pods -n sap-btp-operator
NAME                                                   READY   STATUS    RESTARTS   AGE
sap-btp-operator-controller-manager-6ff9d44ccb-fmlfp   2/2     Running   0          77m
sap-btp-operator-controller-manager-6ff9d44ccb-jqwfb   2/2     Running   0          77m

btp-operator is running

**Comment by LalithManokar** [comment]
HI @cjpark-sapcsa ,

Can you please share the logs of sap-btp-operator?

Since sap-btp-operator is moved to V1 api version try following the below code.
```
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: destination-instance-fiori
spec:
  serviceOfferingName: destination
  servicePlanName: lite
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: destination-binding-fiori
spec:
    serviceInstanceName: destination-instance-fiori
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: xsuaa-instance-fiori
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: xsapp-fiori
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
      - https://*/**
      - http://*/**
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: xsuaa-binding-fiori
spec:
    serviceInstanceName: xsuaa-instance-fiori
```

Regards,
Lalith. S
